---
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.host}:3306/yupi?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: ${db.pw}
  session:
    timeout: 86400
server:
  port: 8080
  servlet:
    context-path: /api
mybatis:
  type-aliases-package: com.zluolan.usercenter.model.domain
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: false
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
